### ISSUE TITLE
TypeError: this.nativeView.tearDown is not a function

### ISSUE THREAD

**Issue by lostation** [nativescript-community/gesturehandler#10]
### Which platform(s) does your issue occur on?
- Android 
- iOS/Android versions 
- emulator

### Please, provide the following version numbers that your issue occurs with:

✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.3.0 version and is up to date.
✔ Component @nativescript/core has 8.3.1 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 8.3.0 version and is up to date.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods update is not required.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.

- "@nativescript/angular": "^14.0.3",
- "@nativescript/core": "8.3.1",
- "@angular-devkit/build-angular": "14.0.5",
- "@angular-eslint/eslint-plugin": "14.0.2",
- "@angular-eslint/eslint-plugin-template": "14.0.2",
- "@angular-eslint/template-parser": "14.0.2",
- "@angular/cli": "~14.0.0",
- "@angular/compiler-cli": "14.0.6",
- "@angular/language-service": "14.0.6",
- "@nativescript/android": "8.3.0",
- "@nativescript/eslint-plugin": "~0.0.4",
- "@nativescript/types": "~8.2.0",
- "@nativescript/webpack": "~5.0.7",
- "@ngtools/webpack": "^14.0.5",
- "@nrwl/angular": "14.4.2",
- "@nrwl/cli": "14.4.2",
- "@nstudio/angular": "14.3.0",
- "@nstudio/nativescript": "14.3.0",
- "@nstudio/nativescript-angular": "14.3.0",
- "@nstudio/web": "14.3.0",
- "@nstudio/web-angular": "14.3.0",
- "@nstudio/xplat": "14.3.0",

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

I'm currently migrating old NS6 to 8...then I've changed RadDrawer for the UI drawer from community as it can handle drawers from each sides...so cool...but I'm even not sure it is linked in any way. From the stack trace below, we can read @nativescript-community/gesturehandler.android.js ...

I didn't get anything from @nativescript-community previously.

I also added @nativescript-community/material things, ripple etc...

- "@nativescript-community/ui-drawer": "~0.1.1",
- "@nativescript-community/ui-material-bottomsheet": "^7.0.24",
- "@nativescript-community/ui-material-button": "^7.0.24",
- "@nativescript-community/ui-material-cardview": "^7.0.24",
- "@nativescript-community/ui-material-ripple": "^7.0.24",
- "@nativescript-community/ui-material-textfield": "^7.0.24",
- "@nativescript-community/ui-material-textview": "^7.0.24",

That error is -> 
disposeNativeView() {
        this.nativeView.tearDown();
}

### Error stack

JS: ERROR TypeError: Class constructor View cannot be invoked without 'new'
  System.err: An uncaught Exception occurred on "main" thread.
  System.err: Calling js method run failed
  System.err: TypeError: this.nativeView.tearDown is not a function
  System.err:
  System.err: StackTrace:
  System.err: disposeNativeView(file: src/webpack:/app/node_modules/@nativescript-community/gesturehandler/gesturehandler.android.js:14:0)
  System.err:   at derivedCtor.<computed>(file: src/webpack:/app/node_modules/@nativescript-community/gesturehandler/gesturehandler.common.js:135:0)
  System.err:   at _tearDownUI(file: src/webpack:/app/node_modules/@nativescript/core/ui/core/view-base/index.js:661:0)
  System.err:   at _removeViewCore(file: src/webpack:/app/node_modules/@nativescript/core/ui/core/view-base/index.js:492:0)
  System.err:   at _removeView(file: src/webpack:/app/node_modules/@nativescript/core/ui/core/view-base/index.js:482:0)
  System.err:   at _removeEntry(file: src/webpack:/app/node_modules/@nativescript/core/ui/frame/frame-common.js:167:0)
  System.err:   at _removeEntry(file: src/webpack:/app/node_modules/@nativescript/core/ui/frame/index.android.js:393:14)
  System.err:   at _updateBackstack(file: src/webpack:/app/node_modules/@nativescript/core/ui/frame/frame-common.js:244:0)
  System.err:   at setCurrent(file: src/webpack:/app/node_modules/@nativescript/core/ui/frame/index.android.js:259:17)
  System.err:   at (file: src/webpack:/app/node_modules/@nativescript/core/ui/frame/fragment.transitions.android.js:553:0)
  System.err:   at timer(file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:2405:0)
  System.err:   at invokeTask(file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:406:0)
  System.err:   at runTask(file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:178:0)
  System.err:   at invokeTask(file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:487:0)
  System.err:   at ZoneTask.invoke(file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:476:0)
  System.err:   at data.args.<computed>(file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:2385:0)
  System.err:   at invoke(file: src/webpack:/app/node_modules/@nativescript/core/timer/index.android.js:18:0)
  System.err:   at invoke(file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:372:0)
  System.err:   at runGuarded(file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:144:0)
  System.err:   at (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:128:0)
  System.err:   at run(file: src/webpack:/app/node_modules/@nativescript/core/timer/index.android.js:22:0)
  System.err:   at com.tns.Runtime.callJSMethodNative(Native Method)
  System.err:   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
  System.err:   at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1175)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1153)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1149)
  System.err:   at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
  System.err:   at android.os.Handler.handleCallback(Handler.java:938)
  System.err:   at android.os.Handler.dispatchMessage(Handler.java:99)
  System.err:   at android.os.Looper.loopOnce(Looper.java:201)
  System.err:   at android.os.Looper.loop(Looper.java:288)
  System.err:   at android.app.ActivityThread.main(ActivityThread.java:7839)
  System.err:   at java.lang.reflect.Method.invoke(Native Method)
  System.err:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by lostation** [comment]
If someone has any idea or hint to solve this issue...or better understand it...Thanks in advance.

**Comment by lostation** [comment]
@nativescript-community/gesturehandler 2.0.5

**Comment by farfromrefug** [comment]
JS@lostation this is your issue `JS: ERROR TypeError: Class constructor View cannot be invoked without 'new'`
might be coming from another plugin. You need to filter through the plugins and their upgrades
