### ISSUE TITLE
Android issue when using with nativescript-barcodescanner plugin TypeError: Cannot read property '128' of null

### ISSUE THREAD

**Issue by rob4226** [nativescript-community/gesturehandler#9]
Hello,
In NativeScript 8 and Angular 12 on Android, when using the [nativescript-barcodescanner plugin](https://github.com/EddyVerbruggen/nativescript-barcodescanner) with the[ nativescript-ui-drawer plugin](https://github.com/nativescript-community/ui-drawer) which relies on this gesturehandler plugin...When I open the barcodescanner (opens in a new window/modal) then close it, then open the side ui-drawer which is a list of buttons for a side menu, **clicking any of the buttons results in crashing on Android with the bellow error:**

```sh
Calling js method onTouch failed
System.err: TypeError: Cannot read property '128' of null
System.err:
System.err: StackTrace:
System.err: androidOnTouchEvent(file: src\webpack:\mobile\gesturehandler\plugin\gestures_override.js:223:44)
System.err:     at (file: src\webpack:\mobile\node_modules\@nativescript\core\ui\core\view\index.android.js:319:0)
```

I tracked down a couple places where I think the problem happens. It seems after the barcodescanner window is closed, the `_detach()` method is called which sets `this._eventData = null;` then in at least two places,  `androidOnTouchEvent`, `emitEvent` try to access `this._eventData` with a subscript notation like `this._eventData[GestureTypes.touch]` but it is null, so it crashes the program in those places.  I put some guards in that set `this._eventData` back to an empty object if it is `null`, like:
```typescript
if (!this._eventData) {
    this._eventData = {};
}
```
_Original code:_
https://github.com/nativescript-community/gesturehandler/blob/f46153f460172127590ff18a5ef03801fd06ad83/src/gestures_override.ts#L273-L283

https://github.com/nativescript-community/gesturehandler/blob/f46153f460172127590ff18a5ef03801fd06ad83/src/gestures_override.ts#L126-L129

https://github.com/nativescript-community/gesturehandler/blob/f46153f460172127590ff18a5ef03801fd06ad83/src/gestures_override.ts#L121-L124

This has stopped my app from crashing and now my ui-drawer menu buttons work but, I am left with one annoying side effect.  Each of my menu button opens up a different modal, **but now there is a white screen on top of any modal I open from the ui-drawer, if I hit the hardware back button at least once, (sometimes it takes 2-3 taps), the white screen will go away and my modal will be under it.  It is almost like there are more frames on top my modal or something.** 

This only happens **after** opening the barcodescanner window. If I restart the app, then try the ui-drawer menu buttons, my modals will open up fine without those crashes, and without those white screens on top of the modals (after I adjusted the code for those null objects).  Do you have any ideas what could at least be causing these white overlays over the modals?  Thank you!!!

**Comment by farfromrefug** [comment]
@Rob4226 thanks for the deep debug!.
By any chance could you create a simple repro project? I will fix it

**Comment by rob4226** [comment]
Hi @farfromrefug, yes I will put one together and post it. Thanks.
